[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         dummy
    Tag          e2e.test
    Dummy        {"message":"hello-from-emulator-e2e"}
    Samples      1

[OUTPUT]
    Name         pubsub
    Match        *
    Project      e2e-project
    Topic        e2e-topic
    Timeout      10000
    Debug        true
